# net architecture
architecture: yolo_v2_resnet50

# log and checkpoint
ckpt_path: ./
ckpt_name: yolo_v2_resnet50

# datasets
data_path: ./data
num_classes: 20
dataset: voc2007
size_list: [320,]
size_change_freq: 160

# training parameters
use_gpu: True
epochs: 160
batch_size: 32
test_batch: 32
eval_freq: 2
print_interval: 10
workers: 4

# multi classifiers used during training
pretrained_backbone: True
#num_classifier: 1
#classifier_weight: [1.,]

# regularization
#mixup: False
#mixup_alpha: 0.4

augmentation:
  normalize: True
  random_crop: True
  random_horizontal_filp: True
  cutout: False
  holes: 1
  length: 8

# optimizer
optimize:
  # type: SGD or Adam
  type: SGD
  weight_decay: 0.0005
  # only for SGD
  momentum: 0.9
  nesterov: True

# learning rate scheduler
lr_scheduler:
  # type: ADAPTIVE or STEP or MultiSTEP or COSINE or HTD
  type: MultiSTEP
  base_lr: 0.001
  # for ADAPTIVE, STEP and MultiSTEP
  lr_mults: 0.1
  # for ADAPTIVE, COSINE and HTD
  min_lr: 0.0
  # only for ADAPTIVE
  mode: max
  patience: 10
  # only for STEP
  step_size: 50
  # only for MultiSTEP
  lr_epochs: [60, 90]
  # only for HTD
  lower_bound: -6.0
  upper_bound: 3.0